### PR TITLE
add search api

### PR DESCRIPTION
**Pull request by kislogic**
# Description

Please provide a detailed description of what was done in this PR

# Changes

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)
- [ ] Changes only for a subset of nodes

# Breaking changes

Please complete this section if any breaking changes have been made, otherwise delete it

# Nodes audience

In case this PR includes changes that must be applied only to a subset of nodes, please specify how you handled it (e.g. by adding a flag with a default value...)

# Checklist

- [ ] I have added at least 2 reviewer or the whole pos-v1 team
- [ ] I have added sufficient documentation in code
- [ ] I will be resolving comments - if any - by pushing each fix in a separate commit and linking the commit hash in the comment reply
- [ ] Created a task in Jira and informed the team for implementation in Erigon client (if applicable)
- [ ] Includes RPC methods changes, and the Notion documentation has been updated

# Cross repository changes

- [ ] This PR requires changes to heimdall
    - In case link the PR here:
- [ ] This PR requires changes to matic-cli
    - In case link the PR here:

## Testing

- [ ] I have added unit tests
- [ ] I have added tests to CI
- [ ] I have tested this code manually on local environment
- [ ] I have tested this code manually on remote devnet using express-cli
- [ ] I have tested this code manually on mumbai
- [ ] I have created new e2e tests into express-cli

### Manual tests

Please complete this section with the steps you performed if you ran manual tests for this functionality, otherwise delete it

# Additional comments

Please post additional comments in this section if you have them, otherwise delete it

### CODE REVIEW

**Comment by pratikspatil024** [comment]
Hi @kislogic, thanks for the PR, please update the description.

**Comment by marcello33** [comment]
Hey @kislogic please fix CI `lint` and `unit-tests`

**Comment by manav2401** [comment]
Hey @kislogic, any updates on this? Please update the description and failing tests before our team reviews this. Thanks!

**Comment by 0xKrishna** [comment]
@kislogic Please provide some context and desc for the team to review this, Also some test cases would be a good plus.

**Comment by temaniarpit27** [comment]
@kislogic Please raise the PR against develop branch and not on master

**Comment by temaniarpit27** [comment]
Closing this for now. Please feel free to reopen when above comments are resolved. We will take a look at this
Thanks

**Pull request closed without merging**
