### PR TITLE
INC-2109 adding workflow chang3es for checksum, pkg creation of deb a…

### PR DESCRIPTION
**Pull request by djpolygon**
This draft PR is a placeholder for some testing purposes related to addition to checksum, package signing, and creation of rpm/deb packages. 

This is a work in progress.

### CODE REVIEW

**Comment by djpolygon** [comment]
Still working on rpm spec files and confirming deb packages work correctly via docker.

**Comment by temaniarpit27** [comment]
Hi
Can you please raise an issue regarding this PR with the purpose and description of the feature you are trying to implement?

**Comment by djpolygon** [comment]
@temaniarpit27 this is still a draft PR, I will add description and details prior to converting to an actual PR.

**Comment by cffls** [comment]
@temaniarpit27 This is about the package signing Daniel @djpolygon is working on.

**Pull request closed without merging**
