### PR TITLE
Added a script to increase the version

### PR DESCRIPTION
**Pull request by pratikspatil024**
Instead of manually updating the version across all the files, use this script and provide all the 4 components of the version, and it will update the version across all the 7 files.

```
$ ./scripts/updateVersion.sh
```

```
The version is of form - VersionMajor.VersionMinor.VersionPatch-VersionMeta
Let's take 0.3.4-beta as an example. Here:
* VersionMajor is - 0
* VersionMinor is - 3
* VersionPatch is - 4
* VersionMeta is  - beta

Now, enter the new version step-by-step below:
* VersionMajor: 0
* VersionMinor: 3
* VersionPatch: 8
* VersionMeta (optional, press enter if not needed): beta  

The new version is: 0.3.8-beta

Updating Version Done

```

### CODE REVIEW

**Comment by marcello33** [comment]
Yep! Was wondering yesterday why this was pending on a branch and never merged
LGTM

**Review by marcello33 — APPROVED** [review]

**Comment by marcello33** [comment]
Actually, can we have such script (slightly modified of course) for `heimdall` too?

**Comment by pratikspatil024** [comment]
Yes, I have created a similar script for heimdall as well. Was facing some issue in testing it.
Here is the [heimdall script](https://github.com/maticnetwork/heimdall/compare/develop...pratik-version-increment)

**Comment by marcello33** [comment]
> Yes @marcello33 , I have created a similar script for heimdall as well. Was facing some issue in testing it. Here is the [heimdall script](https://github.com/maticnetwork/heimdall/compare/develop...pratik-version-increment)

Oh nice, if you get it to work, let's have it merged too
Ping me if you need help

**Comment by pratikspatil024** [comment]
Yes sir! Thank you.

**Review by manav2401 — APPROVED** [review]

**Pull request merged**
