### PR TITLE
core,eth,internal/cli,internal/ethapi: add --rpc.allow-unprotected-txs flag to allow txs to get replayed (for shadow node) 

### PR DESCRIPTION
**Pull request by Raneet10**
# Description

This PR introduces `rpc.allow-unprotected-txs` flag to facilitate replaying of transactions from a different network to a shadow node (i.e a node producing blocks in isolation with the state of the network from which transactions are being relayed). 

# Changes

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)
- [ ] Changes only for a subset of nodes

# Nodes audience

Currently, this flag is only meant to be enabled if we are running a shadow node.

# Checklist

- [x] I have added at least 2 reviewer or the whole pos-v1 team
- [x] I have added sufficient documentation in code
- [x] I will be resolving comments - if any - by pushing each fix in a separate commit and linking the commit hash in the comment reply

## Testing

- [ ] I have added unit tests
- [ ] I have added tests to CI
- [ ] I have tested this code manually on local environment
- [x] I have tested this code manually on remote devnet using express-cli
- [ ] I have tested this code manually on mumbai
- [ ] I have created new e2e tests into express-cli

### CODE REVIEW

**Comment by pgebheim** [comment]
This patch is also useful for testing 4337 so that deterministic deployer contracts can be deployed at the correct address for testing.

cc: @pratikspatil024

**Comment by Raneet10** [comment]
> This patch is also useful for testing 4337 so that deterministic deployer contracts can be deployed at the correct address for testing.
> 
> cc: @pratikspatil024

I'm afraid I don't have much context. But perhaps you could enlighten me on this :)

**Review by pratikspatil024 — COMMENTED** [review]
Please update all the TOML config files.

**Comment by Raneet10** [comment]
Done: [4917fde](https://github.com/maticnetwork/bor/pull/705/commits/4917fde5be2a8c1eb5f6147b1900d52cefcd7dbd)

**Review by temaniarpit27 — APPROVED** [review]

**Review by marcello33 — APPROVED** [review]

**Review by pratikspatil024 — APPROVED** [review]

**Comment by kaber2** [comment]
Just noticed this gem while merging the latest changes. Does anyone actually review these patches?

`
// Exclude transactions with invalid signatures as soon as
// possible and cache senders in transactions before
// obtaining lock

if pool.config.AllowUnprotectedTxs {
        pool.signer = types.NewFakeSigner(tx.ChainId())
`

Why the hell is this changing global pool configuration *inside the transaction add path*?

**Comment by Raneet10** [comment]
Hey @kaber2 , firstly let's please try to watch our tone in these conversations; we're all trying to collaborate here. Secondly, the signer change happens only when `AllowUnprotectedTxs` is set to true (mostly when you're running a shadow forked node) and we override the signer with the chain ID of the network from which the transaction is coming (instead of the local network's) since we're allowing transactions from a different network to be replayed. We can maybe make this change on an upper level of the call stack, which would be logically sound though my initial assumption was that this might result in some repetitive code. Of course, open to your *mild* thoughts as to where this condition should be placed!

**Pull request merged**
