### PR TITLE
fix sender pending txn

### PR DESCRIPTION
**Pull request by temaniarpit27**
https://github.com/ethereum/go-ethereum/issues/23762

### CODE REVIEW

**Comment by ferranbt** [comment]
Please wait until #304 is merged because the tests on the CI are not being executed.

**Comment by ferranbt** [comment]
Do we really have to do this patch on the release branch? We can merge to master right? @vcastellm

**Comment by temaniarpit27** [comment]
closing this
we are already testing new geth version with latest changes and planning it to release it by early next week

**Comment by vcastellm** [comment]
Yeah everything could go to master now

**Comment by ferranbt** [comment]
Are there any unit tests covering this?

**Review by ssandeep — APPROVED** [review]

**Pull request merged**
