### PR TITLE
Added support for miner.recommit flag

### PR DESCRIPTION
**Pull request by pratikspatil024**
We will take this up when working on all the PRs with `MEV` labels.

Linking these two points ([first](https://github.com/maticnetwork/bor/commit/fcb722e4bf5bdda23d4c91da40ab95c9023a80c3#commitcomment-100665900), and [second](https://github.com/maticnetwork/bor/commit/fcb722e4bf5bdda23d4c91da40ab95c9023a80c3#commitcomment-100675141)) mentioned by @thogard785 in this [commit](https://github.com/maticnetwork/bor/commit/fcb722e4bf5bdda23d4c91da40ab95c9023a80c3).

### CODE REVIEW

**Comment by pratikspatil024** [comment]
@thogard785 we decided to take this up as a separate PR and have some discussion around it before merging it.

Feel free to start the discussion here. Thank you.

**Comment by pratikspatil024** [comment]
Screenshot of previous discussion for reference.

Screenshot 2023-02-15 at 3 07 46 PM

**Comment by JekaMas** [comment]
Let's merge issues that doesn't change default values,but only introduce flags @pratikspatil024 @temaniarpit27

**Comment by pratikspatil024** [comment]
Agreed, @JekaMas.

**Review by manav2401 — APPROVED** [review]

**Review by Raneet10 — APPROVED** [review]

**Pull request merged**
