### PR TITLE
new: dev: pos-398 restore geth tests

### PR DESCRIPTION
**Pull request by marcello33**
This PR restores GETH integration tests for bor.
Around 5k tests run successful now.
Skipped ones are tracked via `FIXME POS-618` comment, according to the JIRA issue https://polygon.atlassian.net/browse/POS-618

### CODE REVIEW

**Comment by JekaMas** [comment]
@marcello33 do you need any help,?

**Comment by marcello33** [comment]
> @marcello33 do you need any help,?

Hey @JekaMas, I am not getting notifications for PR comments. My idea is to discuss this together in the call we have planned for today, together with cpu and memory profiling

**Review by JekaMas — APPROVED** [review]
lgtm if CI is 'green'

**Review by JekaMas — CHANGES_REQUESTED** [review]
Could we just skip unrelated to Bor tests without changing the way tests are run?

**Review by JekaMas — APPROVED** [review]
great work!

**Pull request merged**
