### PR TITLE
Apply best practices to Dockerfile

### PR DESCRIPTION
**Pull request by victorcoder**
* Cleanup apk caches after install
* Pin alpine versions for predictable builds

### CODE REVIEW

**Review by temaniarpit27 — DISMISSED** [review]

**Comment by ferranbt** [comment]
LGTM! Are we going to build the new cli (commands) in this PR or in a different one?

**Comment by victorcoder** [comment]
We can leave this PR open until we have everything ready.

**Comment by ferranbt** [comment]
Can you move it then to Draft, otherwise we might merge it unknowingly.

**Comment by victorcoder** [comment]
Currently building the old CLI, building the new one it's as simple as https://github.com/maticnetwork/bor/commit/e58bdfa8e8ac96f4aaf6d3911af5001596ea4e82

We'll create a new PR against `v2` and update docs when it's stable.

**Pull request merged**
