### PR TITLE
Update mumbai config

### PR DESCRIPTION
**Pull request by 0xKrishna**

### CODE REVIEW

**Review by temaniarpit27 — DISMISSED** [review]

**Review by ssandeep — APPROVED** [review]

**Comment by ssandeep** [comment]
Can you check with @vcastellm about builder/files/genesys-testnet-v4.json, I think there was a typo in the filename and he had fixed it already.

**Comment by 0xKrishna** [comment]
@vcastellm Can you please confirm once available.

**Comment by vcastellm** [comment]
Missing the typo fix in `master` 4e746714f6b01cd3900a0d2870d36bde57d64583, I'm going to include it

**Review by vcastellm — APPROVED** [review]
LGTM and included the fix in file name

**Review by temaniarpit27 — APPROVED** [review]

**Pull request merged**
