### PR TITLE
Debug command to trace blocks

### PR DESCRIPTION
**Pull request by ferranbt**
This PR adds a new command to print a JSON output of the trace of a block (by number, tag, hash or bad block hash).

### CODE REVIEW

**Comment by manav2401** [comment]
Added support for getting block trace for ancient blocks (in archive mode) and unit test.

**Comment by vcastellm** [comment]
Please PR against `v0.3.0-dev`

**Comment by manav2401** [comment]
A helper utility which can create and destroy a mock server is added. This will abstract the port handling (primarily for the grpc server and any other if added in future) from the tests.

**Comment by temaniarpit27** [comment]
@ferranbt can you please provide an update on this PR?

**Comment by manav2401** [comment]
Have merged v0.3.0-dev onto this. This is ready to merge.

**Comment by temaniarpit27** [comment]
@manav2401 Please resolve conflicts and merge this

**Pull request closed without merging**
